package model.cards;

public enum SpellTarget {
    ONE_ENEMY,
    ONE_FRIEND,
    HERO_FRIEND,
    HERO_ENEMY,
    ALL_ENEMIES,
    ALL_FRIENDS,
    ONE_FRIND_OR_ENEMY,
    ALL_ENEMIES_IN_ONE_COLUMN,
    ONE_MINION_FRIEND,
    ONE_MINION_ENEMY,
    RANDOM_ENEMY_MINION_AROUND_HERO,
    SQUARE2,
    SQUARE3,
}
